

#ifndef FAI_P2PSERVICE_H
#define	FAI_P2PSERVICE_H
class CNode;
class CDataStream;
enum servicetype
{
 /** Null * */
SC_NULL = 0x00,
/** FULLNODEPLUS* */
SC_FULLNODEPLUS_C = 0x02,
SC_FULLNODEPLUS_S = 0x03,
SC_APP_C = 0x3e,
SC_APP_S = 0x3f,
SC_FULLNODEPLUS_C_GETTX_BYTXID = 0x0200,
SC_FULLNODEPLUS_C_GETTX_BYHEIGHTNTX = 0x0202,
SC_FULLNODEPLUS_C_GETTXOUT_BYTXIDNOUT = 0x0210,
SC_FULLNODEPLUS_C_GETTXOUT_BYHEIGHTNTXNOUT = 0x0212,
SC_FULLNODEPLUS_C_GETDOMAININFO = 0x0220,
SC_FULLNODEPLUS_C_GETUNSPENTTXOUT = 0x0230,
SC_FULLNODEPLUS_C_SEARCHPROMOTEDCONTENT = 0x0240,
SC_FULLNODEPLUS_C_GETFEERATE = 0x0250,

SC_FULLNODEPLUS_S_TX = 0x0301,
SC_FULLNODEPLUS_S_TXOUT = 0x0311,
SC_FULLNODEPLUS_S_DOMAININFO = 0x0321,
SC_FULLNODEPLUS_S_UNSPENTTXOUT = 0x0331,
SC_FULLNODEPLUS_S_PROMOTEDCONTENTS = 0x0341,
SC_FULLNODEPLUS_S_FEERATE = 0x0351,
};
static std::map<int,std::string> mapSCNames=boost::assign::map_list_of
/** Null * */
(SC_NULL,"SC_NULL")
/** FULLNODEPLUS* */
(SC_FULLNODEPLUS_C,"SC_FULLNODEPLUS_C")
(SC_FULLNODEPLUS_S,"SC_FULLNODEPLUS_S")
(SC_APP_C,"SC_APP_C")
(SC_APP_S,"SC_APP_S")
(SC_FULLNODEPLUS_C_GETTX_BYTXID,"SC_FULLNODEPLUS_C_GETTX_BYTXID")
(SC_FULLNODEPLUS_C_GETTX_BYHEIGHTNTX,"SC_FULLNODEPLUS_C_GETTX_BYHEIGHTNTX")
(SC_FULLNODEPLUS_C_GETTXOUT_BYTXIDNOUT,"SC_FULLNODEPLUS_C_GETTXOUT_BYTXIDNOUT")
(SC_FULLNODEPLUS_C_GETTXOUT_BYHEIGHTNTXNOUT,"SC_FULLNODEPLUS_C_GETTXOUT_BYHEIGHTNTXNOUT")
(SC_FULLNODEPLUS_C_GETDOMAININFO,"SC_FULLNODEPLUS_C_GETDOMAININFO")
(SC_FULLNODEPLUS_C_GETUNSPENTTXOUT,"SC_FULLNODEPLUS_C_GETUNSPENTTXOUT")
(SC_FULLNODEPLUS_C_SEARCHPROMOTEDCONTENT,"SC_FULLNODEPLUS_C_SEARCHPROMOTEDCONTENT")
(SC_FULLNODEPLUS_C_GETFEERATE,"SC_FULLNODEPLUS_C_GETFEERATE")
(SC_FULLNODEPLUS_S_TX,"SC_FULLNODEPLUS_S_TX")
(SC_FULLNODEPLUS_S_TXOUT,"SC_FULLNODEPLUS_S_TXOUT")
(SC_FULLNODEPLUS_S_DOMAININFO,"SC_FULLNODEPLUS_S_DOMAININFO")
(SC_FULLNODEPLUS_S_UNSPENTTXOUT,"SC_FULLNODEPLUS_S_UNSPENTTXOUT")
(SC_FULLNODEPLUS_S_PROMOTEDCONTENTS,"SC_FULLNODEPLUS_S_PROMOTEDCONTENTS")
(SC_FULLNODEPLUS_S_FEERATE,"SC_FULLNODEPLUS_S_FEERATE")
;

bool ProcessP2PServiceRequest(CNode* pfrom, CDataStream& vRecv, int64_t nTimeReceived);

#endif	/* FAI_P2PSERVICE_H */

